blank_issues_enabled: true
contact_links:
- name: StoneKeep Discord Server
  url: https://discord.gg/qwwYV6dbcg
  about: For help with running the game, or joining the server, join our Discord server.
